

curl --location --request POST 'https://socket-betzone-newtrading.stg.betzone-multi.tup-cloud.com/api/event-list' \
--header 'Content-Type: application/json' \
--data-raw '{
    "sport": [
        "horseracing"
    ]
}'


###

POST https://socket-betzone-newtrading.stg.betzone-multi.tup-cloud.com/api/event-list
Content-Type: application/json

{
    "sport": [
        "horseracing"
    ]
}

###


GET https://socket-betzone-newtrading.stg.betzone-multi.tup-cloud.com/api/meta/build

###

POST https://socket-betzone-newtrading.stg.betzone-multi.tup-cloud.com/api/event-list
Content-Type: application/json

{
    "sport": ["horseracing"],
    "started": false,
    "time": "next-off",
    "market.display": true,
    "state": "open"
}

###

POST http://127.0.0.1:8888/api/event-list
Content-Type: application/json

{
    "sport": [
        "horseracing"
    ]
}

###

GET http://127.0.0.1:8888/api-proxy.spec.json)